name: Binary Blog
favicon: null
layout_spectrum: 0.74551
typography_spectrum: 0.34086
title: 'Binary Thinktank // Efficiency, Research, Solution Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-18849219-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4a527'
    - '#212221'
    - '#000000'
    - '#aa5500'
    - '#ffbf00'
  brandStrength: 0.1875
  lightness: 0.6847520598676056
  saturation: 0.5
  rhythmicContrast: 0.23777704034000635
purpose: []
